spring:
  application:
    name: ingress-service
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5436/transaction_db
    username: user
    password: 6758
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  flyway:
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: false
    baseline-version: 1
    baseline-on-migrate: true
    loggers: slf4j
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        transaction:
          jta:
            platform: none
    database: postgresql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

app:
  kafka:
    resend:
      fixedDelay: 30
      initialDelay: 30
    topics:
      raw-transactions: raw-transactions

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: system-ingress-service
      environment: dev
  prometheus:
    metrics:
      export:
        enabled: true


server:
  port: 8085
  url: /api/v1/transactions


logging:
  level:
    root: info
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %clr(%-5level) %logger{36} - %msg%n'